# Main text of home
name: Dan Lin
bio: Musings of a Data Scientist

# Image
external-image: false
picture: assets/images/profile.jpg

# Resumé
resume: false

url: http://dan-lin.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# Allow comments on posts
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# Social sites
linkedin: danlin2
github: dan-lin
email: danlinsite@gmail.com

# Define authors
authors:
    danlin:
        name: Dan Lin
        bio: Musings of a Data Scientist
        external-image: false
        picture: assets/images/profile.jpg

# Size of site: normal = 560px / large = 810px
width: large

# Use pagination
# paginate: 5
# paginate_path: "blog/:num/"

# Shows different sections 
about: true
projects: true
experiments: true

# Show the "tags" inside the posts
show-tags: true

# Display links for next and previous posts for the specified categories
post-advance-links: [projects, experiments]

# Display for author block at end of posts
show-author: true

# Display animations
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
    
repository: dan-lin/dan-lin.github.io
